name: Deploy
on:
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN : ${{ secrets.FIREBASE_TOKEN }}
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 18.12.1
#     - run: npm install
#     - run: npm run build
#     - run: npm install -g firebase-tools
#     - run: npm install firebase
#     - run: firebase deploy --only hosting,storage
#       env: 
#           FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
