name: Deploy
on:
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.12.1
    - run: npm install
    - run: npm run build
    - run: npm install -g firebase-tools
    - run: npm install firebase
    - run: npm run deploy
